tasks:
  - init: eval $(gp env NG_CLI_ANALYTICS=false) && cd frontend && npm install
    command: npm run start
  - command: gp open frontend/src/app/gui-model/guimodel.ts
ports:
  - port: 4567
  - port: 4200
    onOpen: open-preview